### ISSUE TITLE
Prepare for internationalization

### ISSUE THREAD

**Issue by bglamadrid** [bglamadrid/trebol-ng#20]
I have not put Angular i18 features into use in this project, but I have added a `/src/text` folder that can prove useful into refactoring labels before moving to that.

**Comment by eLeontev** [comment]
I added base structure for i18n without angulari18n feature since current usage of `messages` are only as an arguments to angular material's modal.

**Comment by eLeontev** [comment]
@bglamadrid  can you also add `hacktoberfest` label to the repo?

**Comment by bglamadrid** [comment]
@eLeontev yes! I'm sorry, I just added it
